import { RULES_TOPICS, TOPIC_LABELS } from '@/content/types';
import { LEARNER_TAXONOMY } from '@/content/learner-signs';
import { SteeringWheelBadge } from '@/ui/SteeringWheelBadge';
import { YieldSignBadge } from '@/ui/YieldSignBadge';
import masterWheelAsset from '@/assets/medals/steering-wheel-base.svg';

const levels = [
  ['Novice', '0%', '--wheel-primary', '#71839a'], ['Learner', '20%', '--brand-light', '#428bca'],
  ['Competent', '45%', '--brand', '#00558c'], ['Proficient', '70%', '--achievement', '#ffb500'], ['Expert', '90%', '--achievement + --mastery', '#d99500 + #9b26b6'],
] as const;
const examTones = ['bronze', 'silver', 'gold', 'platinum'] as const;

export function AchievementShowroom() {
  return <>
    <header className="screen-head"><h1>Achievement Showroom</h1><p>Review study levels, topic medals, section expertise and practice-exam tiers.</p></header>
    <section className="showroom-section"><h2>Study Levels</h2><div className="showroom-levels">
      {levels.map(([label, threshold, token, value], index) => <article className="showroom-card" key={label}><SteeringWheelBadge kind="level" tone={label.toLowerCase() as 'novice' | 'learner' | 'competent' | 'proficient' | 'expert'} width={104} height={104} /><strong>{label}</strong><small>{threshold} · {token}</small><code>{value}</code><span className={`showroom-state showroom-state--${index === 2 ? 'current' : index < 2 ? 'complete' : 'future'}`}>{index === 2 ? 'Current' : index < 2 ? 'Completed' : 'Future'}</span></article>)}
    </div><div className="showroom-rail" aria-label="Five-step Profile rail fixture">{levels.map(([label], index) => <div key={label} data-state={index === 2 ? 'current' : index < 2 ? 'complete' : 'future'}><SteeringWheelBadge kind="level" tone={label.toLowerCase() as 'novice' | 'learner' | 'competent' | 'proficient' | 'expert'} width={index === 2 ? 44 : 34} height={index === 2 ? 44 : 34} /><span>{label}</span></div>)}</div></section>
    <ShowroomTopicSection title="Rules Topic Medals" labels={RULES_TOPICS.map((topic) => TOPIC_LABELS[topic])} tone="rules" />
    <ShowroomTopicSection title="Road Sign Medals" labels={LEARNER_TAXONOMY.map((category) => category.label)} tone="signs" />
    <section className="showroom-section"><h2>Topic Medal States</h2><p className="achievement-copy">Shape communicates achievement family. Colour communicates topic achievement state.</p><div className="showroom-row"><article className="showroom-card showroom-card--wide"><div className="showroom-pair"><SteeringWheelBadge kind="topic" tone="rules" earned={false} width={80} height={80} /><SteeringWheelBadge kind="topic" tone="rules" earned width={80} height={80} /><SteeringWheelBadge kind="topic" tone="rules" earned mastered width={80} height={80} /></div><strong>Rules topic</strong><small>Grey wheel · Blue wheel · Gold wheel</small></article><article className="showroom-card showroom-card--wide"><div className="showroom-pair"><YieldSignBadge earned={false} width={80} height={80} /><YieldSignBadge earned width={80} height={80} /><YieldSignBadge earned mastered width={80} height={80} /></div><strong>Sign topic</strong><small>Grey Yield · Blue Yield · Gold Yield</small></article></div></section>
    <section className="showroom-section"><h2>Section Expertise</h2><div className="showroom-row"><article className="showroom-card showroom-card--wide"><SteeringWheelBadge kind="section" tone="rules" earned width={112} height={112} /><strong>Rules of the Road expert</strong><small>Premium steering wheel</small></article><article className="showroom-card showroom-card--wide"><YieldSignBadge premium earned width={112} height={112} /><strong>Road Signs expert</strong><small>Premium Yield badge</small></article></div></section>
    <section className="showroom-section"><h2>Practice Exam Medals</h2><div className="showroom-row">{examTones.map((tone, index) => <article className="showroom-card" key={tone}><SteeringWheelBadge kind="exam" tone={tone} tier={(index + 1) as 1 | 2 | 3 | 4} earned width={112} height={112} /><strong>Tier {index + 1}</strong><small>{['First full test', 'Passed both parts', 'Consistent', 'Flawless'][index]} · {tone[0]!.toUpperCase() + tone.slice(1)}</small></article>)}</div></section>
    <section className="showroom-section"><h2>Size Test</h2><div className="showroom-size-row">{[24, 32, 40, 48, 64, 72, 96, 128].map((size) => <div key={size}><SteeringWheelBadge kind="topic" tone="rules" width={size} height={size} /><span>{size}px</span></div>)}</div></section>
    <section className="showroom-section"><h2>Master Comparison</h2><div className="showroom-row"><article className="showroom-card"><img src={masterWheelAsset} alt="Master steering-wheel asset" width={128} height={128} /><strong>Master SVG</strong><small>steering-wheel-base.svg</small></article><article className="showroom-card"><SteeringWheelBadge kind="topic" tone="rules" width={128} height={128} /><strong>SteeringWheelBadge</strong><small>Same canonical geometry</small></article></div></section>
    <section className="showroom-section"><h2>States</h2><div className="showroom-row"><article className="showroom-card"><SteeringWheelBadge kind="topic" tone="rules" earned width={88} height={88} /><strong>Traffic signals</strong><small>Earned</small></article><article className="showroom-card"><SteeringWheelBadge kind="topic" tone="rules" earned={false} width={88} height={88} /><strong>Collisions and emergencies</strong><small>Complete this topic</small></article><article className="showroom-card"><SteeringWheelBadge kind="topic" tone="signs" earned={false} width={88} height={88} /><strong>Guide &amp; Information</strong><small>Complete this topic</small></article></div></section>
    <section className="showroom-section"><h2>Multi-instance / Light and Dark</h2><div className="showroom-surface showroom-surface--light"><SteeringWheelBadge kind="level" tone="learner" width={64} height={64} /><SteeringWheelBadge kind="topic" tone="rules" width={64} height={64} /><SteeringWheelBadge kind="topic" tone="signs" width={64} height={64} /><SteeringWheelBadge kind="exam" tone="gold" tier={3} width={64} height={64} /></div><div className="showroom-surface showroom-surface--dark"><SteeringWheelBadge kind="level" tone="learner" width={64} height={64} /><SteeringWheelBadge kind="topic" tone="rules" width={64} height={64} /><SteeringWheelBadge kind="topic" tone="signs" width={64} height={64} /><SteeringWheelBadge kind="exam" tone="gold" tier={3} width={64} height={64} /></div></section>
    <PaletteShowcase />
  </>;
}

function ShowroomTopicSection({ title, labels, tone }: { title: string; labels: readonly string[]; tone: 'rules' | 'signs' }) {
  return <section className="showroom-section"><h2>{title}</h2><div className="showroom-topic-grid">{labels.map((label, index) => <article className="showroom-topic" key={label}>{tone === 'signs' ? <YieldSignBadge earned={index % 3 !== 2} width={64} height={64} /> : <SteeringWheelBadge kind="topic" tone="rules" earned={index % 3 !== 2} width={64} height={64} />}<span>{label}</span><small>{index % 3 === 2 ? 'Unearned · Complete this topic' : 'Earned'}</small></article>)}</div></section>;
}

function PaletteShowcase() {
  const swatches = [['Brand deep', '--brand-deep', '#002b49'], ['Brand', '--brand', '#00558c'], ['Brand light', '--brand-light', '#428bca'], ['Brand soft', '--brand-soft', '#e9f3f9'], ['Achievement', '--achievement', '#ffb500'], ['Mastery', '--mastery', '#9b26b6'], ['Good', '--good', 'existing semantic'], ['Warning', '--warn', 'existing semantic'], ['Bad', '--bad', 'existing semantic'], ['Neutral', '--surface / --bg', 'theme surfaces']];
  return <section className="showroom-section"><h2>App Palette</h2><div className="palette-grid">{swatches.map(([name, token, value]) => <div className="palette-swatch" key={name}><span style={{ background: `var(${token?.split(' / ')[0] ?? '--surface'})` }} /><strong>{name}</strong><small>{token}</small><code>{value}</code></div>)}</div><div className="palette-samples"><button className="btn btn-primary">Primary action</button><button className="btn btn-secondary">Secondary</button><span className="showroom-selected">Selected tab</span><span className="showroom-progress"><i /></span><span className="showroom-feedback showroom-feedback--good">Success</span><span className="showroom-feedback showroom-feedback--warn">Warning</span><span className="showroom-feedback showroom-feedback--bad">Error</span></div></section>;
}
