/**
 * Font Awesome Pro icons, rendered through the hosted Kit.
 *
 * These glyphs are Font Awesome **Pro**. Pro artwork is licensed per seat and
 * cannot be redistributed, so it must not live in a public repository — not as
 * SVG files, not as extracted path data, not as webfonts, not as the Pro npm
 * packages. What this file contains is only icon *names*, which are ordinary
 * identifiers.
 *
 * The deployed site loads the artwork at runtime from the maintainer's hosted
 * Kit (configured in app.identity.json, injected by vite.config.ts). The Kit
 * runs in SVG-with-JS mode: it finds `<i class="app-icon fa-regular fa-…">` elements and
 * replaces each with an inline `<svg>`, carrying the original element's classes
 * across. That last detail is what lets the app's existing `… svg { width: … }`
 * rules keep sizing icons exactly as before.
 *
 * **If the Kit does not load** — a contributor without a Pro licence, a blocked
 * request, an offline first visit — the `<i>` simply stays an `<i>`. It keeps
 * its reserved box (see `.app-icon` in styles.css) so nothing reflows, and every
 * control it appears in already carries a text label. The app is fully usable
 * with no icons at all; that is a deliberate property, not an accident.
 *
 * Free-tier icons are NOT here. They stay bundled in `icons.tsx`, because
 * CC BY 4.0 artwork can be redistributed and bundling keeps them working
 * offline. Only the Pro subset depends on the network.
 */

import type { HTMLAttributes } from 'react';

/** Classic styles this app uses. The icon language is Regular throughout. */
export type IconStyle = 'fa-regular' | 'fa-solid';

export type IconProps = Omit<HTMLAttributes<HTMLElement>, 'children'> & {
  /**
   * Accessible name. Supply it only when the icon is the sole carrier of
   * meaning; otherwise leave it off and the icon stays hidden from assistive
   * technology so adjacent text is not announced twice.
   */
  title?: string;
};

/**
 * Renders one Kit icon.
 *
 * `app-icon` is this project's own class. It deliberately sits OUTSIDE Font
 * Awesome's `fa-` namespace: FA's parser treats the first `fa-*` class it sees
 * as the icon name, so a marker called `fa-icon` would make every glyph
 * resolve as an icon named "icon". Its job is to mark the element as an icon
 * slot so the stylesheet can reserve its box before — or without — the Kit
 * ever loading.
 */
export function Icon({
  name,
  iconStyle = 'fa-regular',
  title,
  className,
  ...props
}: IconProps & { name: string; iconStyle?: IconStyle }) {
  const classes = ['app-icon', iconStyle, `fa-${name}`, className].filter(Boolean).join(' ');

  return (
    <i
      className={classes}
      role={title ? 'img' : undefined}
      aria-label={title}
      aria-hidden={title ? undefined : true}
      {...props}
    />
  );
}

/*
 * The Pro glyphs this app uses, unchanged from the previously bundled set.
 *
 * Written out as explicit named components rather than generated by a factory:
 * one line each, greppable by icon name, and unambiguous to tooling that has to
 * tell a component from a constant.
 *
 * Three are Pro-only — book-open-cover, diamond-turn-right and ballot-check —
 * and carry the primary navigation. The rest exist in the free tier only as
 * Solid, and Regular is what keeps one consistent icon language across the app.
 */

/* Primary navigation */
export function LearnIcon(props: IconProps) {
  return <Icon name="book-open-cover" {...props} />;
}
export function SignsIcon(props: IconProps) {
  return <Icon name="diamond-turn-right" {...props} />;
}
export function PracticeIcon(props: IconProps) {
  return <Icon name="ballot-check" {...props} />;
}

/* Learner state */
export function XpIcon(props: IconProps) {
  return <Icon name="bolt" {...props} />;
}
export function StreakIcon(props: IconProps) {
  return <Icon name="fire" {...props} />;
}
export function MedalIcon(props: IconProps) {
  return <Icon name="medal" {...props} />;
}
export function AwardIcon(props: IconProps) {
  return <Icon name="award" {...props} />;
}
export function WeakAreaIcon(props: IconProps) {
  return <Icon name="triangle-exclamation" {...props} />;
}

/* Navigation affordances */
export function BackIcon(props: IconProps) {
  return <Icon name="chevron-left" {...props} />;
}
export function ChevronIcon(props: IconProps) {
  return <Icon name="chevron-right" {...props} />;
}
export function ArrowRightIcon(props: IconProps) {
  return <Icon name="arrow-right" {...props} />;
}
export function ExternalIcon(props: IconProps) {
  return <Icon name="up-right-from-square" {...props} />;
}
